
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fahad
 */
public class BreakFast extends javax.swing.JFrame {

    /**
     * Creates new form BreakFast
     */
    double a;
    String d = "";

    public BreakFast() {
        initComponents();
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        plainCheckBox = new javax.swing.JCheckBox();
        butterCheckBox = new javax.swing.JCheckBox();
        garlicCheckBox = new javax.swing.JCheckBox();
        kashmeriCheckBox = new javax.swing.JCheckBox();
        parataCheckBox = new javax.swing.JCheckBox();
        plainNaanTextField = new javax.swing.JTextField();
        butterNaanTextField = new javax.swing.JTextField();
        garlicNaanTextField = new javax.swing.JTextField();
        kashmeriTextField = new javax.swing.JTextField();
        parataTextField = new javax.swing.JTextField();
        esternCheckBox = new javax.swing.JCheckBox();
        westernCheckBox = new javax.swing.JCheckBox();
        bostonCheckBox = new javax.swing.JCheckBox();
        veggieCheckBox = new javax.swing.JCheckBox();
        spanishCheckBox = new javax.swing.JCheckBox();
        easternTextField = new javax.swing.JTextField();
        westernTextField = new javax.swing.JTextField();
        bostonTextField = new javax.swing.JTextField();
        veggieTextField = new javax.swing.JTextField();
        spanishTextField = new javax.swing.JTextField();
        plainpCheckBox = new javax.swing.JCheckBox();
        bluberryCheckBox = new javax.swing.JCheckBox();
        appleCheckBox = new javax.swing.JCheckBox();
        plainpTextField = new javax.swing.JTextField();
        bluberryTextField = new javax.swing.JTextField();
        appleTextField = new javax.swing.JTextField();
        cowCheckBox = new javax.swing.JCheckBox();
        muttonbCheckBox = new javax.swing.JCheckBox();
        chickenCheckBox = new javax.swing.JCheckBox();
        beefCheckBox = new javax.swing.JCheckBox();
        muttonCheckBox = new javax.swing.JCheckBox();
        cowTextField = new javax.swing.JTextField();
        muttonbTextField = new javax.swing.JTextField();
        chickenTextField = new javax.swing.JTextField();
        beefTextField = new javax.swing.JTextField();
        muttonTextField = new javax.swing.JTextField();
        teaCheckBox = new javax.swing.JCheckBox();
        hotCoffeecheckbox = new javax.swing.JCheckBox();
        coldCheckBox = new javax.swing.JCheckBox();
        hotChoCheckBox = new javax.swing.JCheckBox();
        milkCheckBox = new javax.swing.JCheckBox();
        ApplejCheckBox = new javax.swing.JCheckBox();
        MangoCheckBox = new javax.swing.JCheckBox();
        oreoCheckBox = new javax.swing.JCheckBox();
        orangeCheckBox = new javax.swing.JCheckBox();
        teaTextField = new javax.swing.JTextField();
        hotcoffeeTextField = new javax.swing.JTextField();
        coldTextField = new javax.swing.JTextField();
        hotChoTextField = new javax.swing.JTextField();
        milkTextField = new javax.swing.JTextField();
        applejTextField = new javax.swing.JTextField();
        mangoTextField = new javax.swing.JTextField();
        oreoTextField = new javax.swing.JTextField();
        orangeTextField = new javax.swing.JTextField();
        sp1CheckBox = new javax.swing.JCheckBox();
        sp2CheckBox = new javax.swing.JCheckBox();
        sp3CheckBox = new javax.swing.JCheckBox();
        sp4CheckBox = new javax.swing.JCheckBox();
        sp1TextField = new javax.swing.JTextField();
        sp2TextField = new javax.swing.JTextField();
        sp3TextField = new javax.swing.JTextField();
        sp4TextField = new javax.swing.JTextField();
        vegCheckBox = new javax.swing.JCheckBox();
        dalCheckBox = new javax.swing.JCheckBox();
        vegTextField = new javax.swing.JTextField();
        dalTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        plainCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        plainCheckBox.setText("Plain Naan");
        plainCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(plainCheckBox);
        plainCheckBox.setBounds(40, 80, 130, 25);

        butterCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butterCheckBox.setText("Butter Naan");
        jPanel1.add(butterCheckBox);
        butterCheckBox.setBounds(40, 110, 130, 25);

        garlicCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        garlicCheckBox.setText("Garlic Naan");
        jPanel1.add(garlicCheckBox);
        garlicCheckBox.setBounds(40, 140, 130, 25);

        kashmeriCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kashmeriCheckBox.setText("Kashmeri Naan");
        kashmeriCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kashmeriCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(kashmeriCheckBox);
        kashmeriCheckBox.setBounds(40, 170, 130, 25);

        parataCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parataCheckBox.setText("Parata");
        jPanel1.add(parataCheckBox);
        parataCheckBox.setBounds(40, 200, 130, 25);
        jPanel1.add(plainNaanTextField);
        plainNaanTextField.setBounds(180, 80, 30, 30);
        jPanel1.add(butterNaanTextField);
        butterNaanTextField.setBounds(180, 110, 30, 30);
        jPanel1.add(garlicNaanTextField);
        garlicNaanTextField.setBounds(180, 140, 30, 30);
        jPanel1.add(kashmeriTextField);
        kashmeriTextField.setBounds(180, 170, 30, 30);
        jPanel1.add(parataTextField);
        parataTextField.setBounds(180, 200, 30, 30);

        esternCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        esternCheckBox.setText("Eastern Omelete");
        jPanel1.add(esternCheckBox);
        esternCheckBox.setBounds(40, 280, 140, 25);

        westernCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        westernCheckBox.setText("Western Omlete");
        jPanel1.add(westernCheckBox);
        westernCheckBox.setBounds(40, 320, 140, 25);

        bostonCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bostonCheckBox.setText("Boston Omlete");
        jPanel1.add(bostonCheckBox);
        bostonCheckBox.setBounds(40, 360, 140, 25);

        veggieCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        veggieCheckBox.setText("Veggie Omlete");
        jPanel1.add(veggieCheckBox);
        veggieCheckBox.setBounds(40, 400, 140, 25);

        spanishCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spanishCheckBox.setText("Spanish Omlete");
        jPanel1.add(spanishCheckBox);
        spanishCheckBox.setBounds(40, 440, 140, 25);

        easternTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easternTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(easternTextField);
        easternTextField.setBounds(200, 280, 30, 30);
        jPanel1.add(westernTextField);
        westernTextField.setBounds(200, 320, 30, 30);
        jPanel1.add(bostonTextField);
        bostonTextField.setBounds(200, 360, 30, 30);
        jPanel1.add(veggieTextField);
        veggieTextField.setBounds(200, 400, 30, 30);
        jPanel1.add(spanishTextField);
        spanishTextField.setBounds(200, 440, 30, 30);

        plainpCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        plainpCheckBox.setText("Plain Pancake");
        jPanel1.add(plainpCheckBox);
        plainpCheckBox.setBounds(40, 510, 150, 25);

        bluberryCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bluberryCheckBox.setText("Bluberry Pancake");
        jPanel1.add(bluberryCheckBox);
        bluberryCheckBox.setBounds(40, 550, 150, 25);

        appleCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        appleCheckBox.setText("Apple Pancake");
        jPanel1.add(appleCheckBox);
        appleCheckBox.setBounds(40, 590, 150, 25);
        jPanel1.add(plainpTextField);
        plainpTextField.setBounds(200, 510, 30, 30);
        jPanel1.add(bluberryTextField);
        bluberryTextField.setBounds(200, 550, 30, 30);

        appleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(appleTextField);
        appleTextField.setBounds(200, 590, 30, 30);

        cowCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cowCheckBox.setText("Cow Brain Curry");
        jPanel1.add(cowCheckBox);
        cowCheckBox.setBounds(260, 80, 160, 25);

        muttonbCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        muttonbCheckBox.setText("Mutton Brain Curry");
        jPanel1.add(muttonbCheckBox);
        muttonbCheckBox.setBounds(260, 110, 160, 25);

        chickenCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chickenCheckBox.setText("Chicken ");
        jPanel1.add(chickenCheckBox);
        chickenCheckBox.setBounds(260, 140, 160, 25);

        beefCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        beefCheckBox.setText("Beef Kala Bhuna");
        jPanel1.add(beefCheckBox);
        beefCheckBox.setBounds(260, 170, 160, 25);

        muttonCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        muttonCheckBox.setText("Mutton ");
        jPanel1.add(muttonCheckBox);
        muttonCheckBox.setBounds(260, 200, 160, 25);
        jPanel1.add(cowTextField);
        cowTextField.setBounds(450, 80, 30, 30);
        jPanel1.add(muttonbTextField);
        muttonbTextField.setBounds(450, 110, 30, 30);
        jPanel1.add(chickenTextField);
        chickenTextField.setBounds(450, 140, 30, 30);
        jPanel1.add(beefTextField);
        beefTextField.setBounds(450, 170, 30, 30);
        jPanel1.add(muttonTextField);
        muttonTextField.setBounds(450, 200, 30, 30);

        teaCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        teaCheckBox.setText("Tea");
        jPanel1.add(teaCheckBox);
        teaCheckBox.setBounds(260, 280, 110, 30);

        hotCoffeecheckbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hotCoffeecheckbox.setText("Hot Coffee");
        jPanel1.add(hotCoffeecheckbox);
        hotCoffeecheckbox.setBounds(260, 320, 110, 30);

        coldCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coldCheckBox.setText("Cold Coffee");
        jPanel1.add(coldCheckBox);
        coldCheckBox.setBounds(260, 360, 130, 30);

        hotChoCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hotChoCheckBox.setText("Hot Chocolate");
        jPanel1.add(hotChoCheckBox);
        hotChoCheckBox.setBounds(260, 400, 130, 30);

        milkCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        milkCheckBox.setText("Milk Shake");
        jPanel1.add(milkCheckBox);
        milkCheckBox.setBounds(260, 440, 130, 30);

        ApplejCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ApplejCheckBox.setText("Apple Juice");
        jPanel1.add(ApplejCheckBox);
        ApplejCheckBox.setBounds(260, 480, 130, 30);

        MangoCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MangoCheckBox.setText("Mango Juice");
        jPanel1.add(MangoCheckBox);
        MangoCheckBox.setBounds(260, 520, 130, 30);

        oreoCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oreoCheckBox.setText("Oreo Shake");
        jPanel1.add(oreoCheckBox);
        oreoCheckBox.setBounds(260, 560, 130, 30);

        orangeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orangeCheckBox.setText("Orange Juice");
        jPanel1.add(orangeCheckBox);
        orangeCheckBox.setBounds(260, 600, 130, 30);
        jPanel1.add(teaTextField);
        teaTextField.setBounds(450, 280, 30, 30);
        jPanel1.add(hotcoffeeTextField);
        hotcoffeeTextField.setBounds(450, 320, 30, 30);
        jPanel1.add(coldTextField);
        coldTextField.setBounds(450, 360, 30, 30);
        jPanel1.add(hotChoTextField);
        hotChoTextField.setBounds(450, 400, 30, 30);
        jPanel1.add(milkTextField);
        milkTextField.setBounds(450, 440, 30, 30);
        jPanel1.add(applejTextField);
        applejTextField.setBounds(450, 480, 30, 30);
        jPanel1.add(mangoTextField);
        mangoTextField.setBounds(450, 520, 30, 30);
        jPanel1.add(oreoTextField);
        oreoTextField.setBounds(450, 560, 30, 30);
        jPanel1.add(orangeTextField);
        orangeTextField.setBounds(450, 600, 30, 30);

        sp1CheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sp1CheckBox.setText("Two French Toast with two Eggs");
        sp1CheckBox.setToolTipText("");
        jPanel1.add(sp1CheckBox);
        sp1CheckBox.setBounds(570, 80, 260, 25);

        sp2CheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sp2CheckBox.setText("Two French Toast with Bacon");
        jPanel1.add(sp2CheckBox);
        sp2CheckBox.setBounds(570, 120, 250, 25);

        sp3CheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sp3CheckBox.setText("Two Pancakes With Bacon");
        jPanel1.add(sp3CheckBox);
        sp3CheckBox.setBounds(570, 160, 250, 25);

        sp4CheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sp4CheckBox.setText("Two Pancakes With Two Eggs");
        jPanel1.add(sp4CheckBox);
        sp4CheckBox.setBounds(570, 200, 250, 25);
        jPanel1.add(sp1TextField);
        sp1TextField.setBounds(965, 80, 40, 30);
        jPanel1.add(sp2TextField);
        sp2TextField.setBounds(965, 120, 40, 30);
        jPanel1.add(sp3TextField);
        sp3TextField.setBounds(965, 160, 40, 30);
        jPanel1.add(sp4TextField);
        sp4TextField.setBounds(965, 200, 40, 30);

        vegCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vegCheckBox.setText("Vegetable");
        jPanel1.add(vegCheckBox);
        vegCheckBox.setBounds(570, 300, 110, 25);

        dalCheckBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dalCheckBox.setText("Dal");
        jPanel1.add(dalCheckBox);
        dalCheckBox.setBounds(570, 340, 110, 25);
        jPanel1.add(vegTextField);
        vegTextField.setBounds(745, 300, 40, 30);
        jPanel1.add(dalTextField);
        dalTextField.setBounds(745, 340, 40, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(610, 600, 80, 23);

        jButton2.setText("Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(830, 600, 80, 23);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 600, 80, 23);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(940, 600, 80, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Specials");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(580, 50, 80, 20);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(570, 380, 460, 190);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Regular Item");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 250, 110, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Drinks");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 260, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Meat Item");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 50, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Pancake");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 480, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Omelete");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 250, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Naan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 50, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Breakfast");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 0, 230, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/le-champ-des-lunes-restaurant-gastronomique-au-coeur-du-luberon-fond-background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 800);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Butter Naan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 100, 100, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kashmeriCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kashmeriCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kashmeriCheckBoxActionPerformed

    private void appleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appleTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(" ");
        a = 0;

        esternCheckBox.setSelected(false);
        easternTextField.setText("");

        plainCheckBox.setSelected(false);
        plainNaanTextField.setText("");

        butterCheckBox.setSelected(false);
        butterNaanTextField.setText(" ");

        garlicCheckBox.setSelected(false);
        garlicNaanTextField.setText(" ");

        kashmeriCheckBox.setSelected(false);
        kashmeriTextField.setText(" ");

        parataCheckBox.setSelected(false);
        parataTextField.setText(" ");

        esternCheckBox.setSelected(false);
        easternTextField.setText(" ");

        westernCheckBox.setSelected(false);
        westernTextField.setText(" ");

        bostonCheckBox.setSelected(false);
        bostonTextField.setText(" ");

        veggieCheckBox.setSelected(false);
        veggieTextField.setText(" ");

        spanishCheckBox.setSelected(false);
        spanishTextField.setText(" ");

        plainpCheckBox.setSelected(false);
        plainpTextField.setText(" ");

        bluberryCheckBox.setSelected(false);
        bluberryTextField.setText(" ");

        appleCheckBox.setSelected(false);
        appleTextField.setText(" ");

        cowCheckBox.setSelected(false);
        cowTextField.setText(" ");

        muttonbCheckBox.setSelected(false);
        muttonbTextField.setText(" ");

        chickenCheckBox.setSelected(false);
        chickenTextField.setText(" ");

        beefCheckBox.setSelected(false);
        beefTextField.setText(" ");

        muttonCheckBox.setSelected(false);
        muttonTextField.setText(" ");

        teaCheckBox.setSelected(false);
        teaTextField.setText(" ");

        hotCoffeecheckbox.setSelected(false);
        hotcoffeeTextField.setText(" ");

        coldCheckBox.setSelected(false);
        coldTextField.setText(" ");

        hotChoCheckBox.setSelected(false);
        hotChoTextField.setText(" ");

        milkCheckBox.setSelected(false);
        milkTextField.setText(" ");

        ApplejCheckBox.setSelected(false);
        appleTextField.setText(" ");

        MangoCheckBox.setSelected(false);
        mangoTextField.setText(" ");

        oreoCheckBox.setSelected(false);
        oreoTextField.setText(" ");

        orangeCheckBox.setSelected(false);
        orangeTextField.setText(" ");

        sp1CheckBox.setSelected(false);
        sp1TextField.setText(" ");

        sp2CheckBox.setSelected(false);
        sp2TextField.setText(" ");

        sp3CheckBox.setSelected(false);
        sp3TextField.setText(" ");

        sp4CheckBox.setSelected(false);
        sp4TextField.setText(" ");

        vegCheckBox.setSelected(false);
        vegTextField.setText(" ");

        dalCheckBox.setSelected(false);
        dalTextField.setText(" ");


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        FoodSession fs = new FoodSession();
        fs.setVisible(true);
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("E yyyy/MM/dd   HH-mm-ss");

        int b = 0;
        b++;
        File f = new File("D:\\History.txt");
        FileWriter fw = null;
        try {
            fw = new FileWriter(f, true);
        } catch (IOException ex) {
            Logger.getLogger(BreakFast.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedWriter bw = new BufferedWriter(fw);
        try {
            bw.newLine();
            jTextArea1.setText("\nFOOD SQUARE " + "\n" + sdf.format(d) + "\n" + "FOOD NAME      QTY" + "\n");

            bw.append("FOOD SQUARE ");
            bw.newLine();
            bw.append(sdf.format(d));
            bw.newLine();
            bw.append("FOOD NAME      QTY");
            bw.newLine();

            if (plainCheckBox.isSelected()) {
                try {
                    double plain;
                    plain = Double.parseDouble(plainNaanTextField.getText());
                    a = a + plain * 20;
                    bw.append("Plain Naan ");
                    bw.append(plainNaanTextField.getText());
                    bw.newLine();

                    jTextArea1.append("Plain Naan" + "   " + plainNaanTextField.getText() + "\n");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Input only number ");
                }

            }
            if (butterCheckBox.isSelected()) {
                try {
                    double butter;
                    butter = Double.parseDouble(butterNaanTextField.getText());
                    a = a + butter * 30;
                    jTextArea1.append("Butter Naan" + "   " + butterNaanTextField.getText() + "\n");
                    bw.append("Butter Naan Naan ");
                    bw.append(butterNaanTextField.getText());
                    bw.newLine();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Input only number ");
                }

            }
            if (garlicCheckBox.isSelected()) {
                try {
                    double garlic;
                    garlic = Double.parseDouble(garlicNaanTextField.getText());
                    a = a + garlic * 35;
                    jTextArea1.append("Garlic Naan" + "   " + garlicNaanTextField.getText() + "\n");
                    bw.append("Garlic Naan ");
                    bw.append(garlicNaanTextField.getText());
                    bw.newLine();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Input only number ");
                }

            }
            if (kashmeriCheckBox.isSelected()) {
                try {
                    double kashmeri;
                    kashmeri = Double.parseDouble(kashmeriTextField.getText());
                    a = a + kashmeri * 50;
                    jTextArea1.append("Kashmeri Naan" + "   " + kashmeriTextField.getText() + "\n");
                    bw.append("Kashmeri Naan ");
                    bw.append(kashmeriTextField.getText());
                    bw.newLine();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Input only number ");
                }
            }
            if (parataCheckBox.isSelected()) {
                double parata;
                parata = Double.parseDouble(parataTextField.getText());
                a = a + parata * 15;
                jTextArea1.append("Parata " + "   " + parataTextField.getText() + "\n");
                bw.append("Parata ");
                bw.append(parataTextField.getText());
                bw.newLine();
            }
            if (esternCheckBox.isSelected()) {
                double estern;
                estern = Double.parseDouble(easternTextField.getText());
                a = a + estern * 27;
                jTextArea1.append("Eastern Omelete " + "   " + easternTextField.getText() + "\n");
                bw.append("Eastern Omelete ");
                bw.append(easternTextField.getText());
                bw.newLine();
            }
            if (westernCheckBox.isSelected()) {
                double western;
                western = Double.parseDouble(westernTextField.getText());
                a = a + western * 30;
                jTextArea1.append("Western Omelete " + "   " + westernTextField.getText() + "\n");
                bw.append("Western Omelete ");
                bw.append(westernTextField.getText());
                bw.newLine();
            }
            if (bostonCheckBox.isSelected()) {
                double boston;
                boston = Double.parseDouble(bostonTextField.getText());
                a = a + boston * 35;

                jTextArea1.append("Boston Omelete " + "   " + bostonTextField.getText() + "\n");
                bw.append("Boston Omelete ");
                bw.append(bostonTextField.getText());
                bw.newLine();
            }
            if (veggieCheckBox.isSelected()) {
                double veggi;
                veggi = Double.parseDouble(veggieTextField.getText());
                a = a + veggi * 34;
                jTextArea1.append("Veggie Omelete " + "   " + veggieTextField.getText() + "\n");
                bw.append("Veggie Omelete ");
                bw.append(veggieTextField.getText());
                bw.newLine();

            }
            if (spanishCheckBox.isSelected()) {
                double spanish;
                spanish = Double.parseDouble(spanishTextField.getText());
                a = a + spanish * 40;
                jTextArea1.append("Spanish Omelete " + "   " + spanishTextField.getText() + "\n");
            }
            if (plainpCheckBox.isSelected()) {
                double plain;
                plain = Double.parseDouble(plainpTextField.getText());
                a = a + plain * 220;
                jTextArea1.append("Plain Pancake " + "   " + plainpTextField.getText() + "\n");
            }
            if (bluberryCheckBox.isSelected()) {
                double bluberry;
                bluberry = Double.parseDouble(bluberryTextField.getText());
                a = a + bluberry * 300;
                jTextArea1.append("Bluberry Pancake " + "   " + bluberryTextField.getText() + "\n");
                bw.append("Bluberry Pancake ");
                bw.append(bluberryTextField.getText());
                bw.newLine();
            }
            if (appleCheckBox.isSelected()) {
                double apple;
                apple = Double.parseDouble(appleTextField.getText());
                a = a + apple * 290;
                jTextArea1.append("Apple Pancake " + "     " + appleTextField.getText() + "\n");
                bw.append("Apple Pancake ");
                bw.append(appleTextField.getText());
                bw.newLine();
            }
            if (cowCheckBox.isSelected()) {
                double cow;
                cow = Double.parseDouble(cowTextField.getText());
                a = a + cow * 250;

                jTextArea1.append("Cow Brain Curry " + "     " + cowTextField.getText() + "\n");
                bw.append("Cow Brain Curry ");
                bw.append(cowTextField.getText());
                bw.newLine();
            }
            if (muttonbCheckBox.isSelected()) {
                double mutton;
                mutton = Double.parseDouble(muttonbTextField.getText());
                a = a + mutton * 260;
                jTextArea1.append("Mutton Brain Curry " + "     " + muttonbTextField.getText() + "\n");
                bw.append("Mutton Brain Curry ");
                bw.append(muttonbTextField.getText());
                bw.newLine();
            }
            if (chickenCheckBox.isSelected()) {
                double chicken;
                chicken = Double.parseDouble(chickenTextField.getText());
                a = a + chicken * 240;
                jTextArea1.append("Chicken " + "     " + chickenTextField.getText() + "\n");
                bw.append("Chicken ");
                bw.append(chickenTextField.getText());
                bw.newLine();
            }
            if (beefCheckBox.isSelected()) {
                double beef;
                beef = Double.parseDouble(beefTextField.getText());
                a = a + beef * 300;
                jTextArea1.append("Beef Kala Bhuna " + "     " + beefTextField.getText() + "\n");
                bw.append("Beef Kala GHuna ");
                bw.append(beefTextField.getText());
                bw.newLine();
            }
            if (muttonCheckBox.isSelected()) {
                double mutton;
                mutton = Double.parseDouble(muttonTextField.getText());
                a = a + mutton * 310;
                jTextArea1.append("Mutton " + "     " + muttonTextField.getText() + "\n");
                bw.append("Muuton ");
                bw.append(muttonTextField.getText());
                bw.newLine();
            }
            if (teaCheckBox.isSelected()) {
                double tea;
                tea = Double.parseDouble(teaTextField.getText());
                a = a + tea * 30;
                jTextArea1.append("Tea          " + "     " + teaTextField.getText() + "\n");
                bw.append("Tea ");
                bw.append(teaTextField.getText());
                bw.newLine();
            }
            if (hotCoffeecheckbox.isSelected()) {
                double hotCoffee;
                hotCoffee = Double.parseDouble(hotcoffeeTextField.getText());
                a = a + hotCoffee * 120;
                jTextArea1.append("Hot Coffeee       " + "     " + hotcoffeeTextField.getText() + "\n");
                bw.append("Hot Coffee ");
                bw.append(hotcoffeeTextField.getText());
                bw.newLine();
            }
            if (coldCheckBox.isSelected()) {
                double cold;
                cold = Double.parseDouble(coldTextField.getText());
                a = a + cold * 120;
                jTextArea1.append("Cold Coffee     " + "     " + coldTextField.getText() + "\n");
                bw.append("Cold Coffee ");
                bw.append(coldTextField.getText());
                bw.newLine();
            }
            if (hotChoCheckBox.isSelected()) {
                double hotc;
                hotc = Double.parseDouble(hotChoTextField.getText());
                a = a + hotc * 170;
                jTextArea1.append("Hot Chocolate    " + "     " + hotChoTextField.getText() + "\n");
                bw.append("Hot Chocololate ");
                bw.append(hotChoTextField.getText());
                bw.newLine();
            }
            if (milkCheckBox.isSelected()) {
                double milk;
                milk = Double.parseDouble(milkTextField.getText());
                a = a + milk * 160;
                jTextArea1.append("Milk Shake    " + "     " + milkTextField.getText() + "\n");
                bw.append("Milk Shake ");
                bw.append(milkTextField.getText());
                bw.newLine();
            }
            if (ApplejCheckBox.isSelected()) {
                double apple;
                apple = Double.parseDouble(applejTextField.getText());
                a = a + apple * 150;
                jTextArea1.append("Apple Juice    " + "     " + applejTextField.getText() + "\n");
                bw.append("Apple Juice ");
                bw.append(applejTextField.getText());
                bw.newLine();
            }
            if (MangoCheckBox.isSelected()) {
                double mango;
                mango = Double.parseDouble(mangoTextField.getText());
                a = a + mango * 180;
                jTextArea1.append("Mango Juice     " + "     " + mangoTextField.getText() + "\n");
                bw.append("Mango Juice ");
                bw.append(mangoTextField.getText());
                bw.newLine();
            }
            if (oreoCheckBox.isSelected()) {
                double oreo;
                oreo = Double.parseDouble(oreoTextField.getText());
                a = a + oreo * 190;
                jTextArea1.append("Oreo Shake     " + "     " + oreoTextField.getText() + "\n");
                bw.append("Oreo Shake ");
                bw.append(oreoTextField.getText());
                bw.newLine();
            }
            if (orangeCheckBox.isSelected()) {
                double orange;
                orange = Double.parseDouble(orangeTextField.getText());
                a = a + orange * 100;
                jTextArea1.append("Orrange Juice    " + "     " + orangeTextField.getText() + "\n");
                bw.append("Orrange Juice ");
                bw.append(orangeTextField.getText());
                bw.newLine();
            }
            if (sp1CheckBox.isSelected()) {
                double sp1;
                sp1 = Double.parseDouble(sp1TextField.getText());
                a = a + sp1 * 250;
                jTextArea1.append("Two French Toast with two Eggs " + "     " + sp1TextField.getText() + "\n");
                bw.append("Two French Toast with two Eggs ");
                bw.append(sp1TextField.getText());
                bw.newLine();
            }
            if (sp2CheckBox.isSelected()) {
                double sp2;
                sp2 = Double.parseDouble(sp2TextField.getText());
                a = a + sp2 * 290;
                jTextArea1.append("Two French Toast with Bacon " + "     " + sp2TextField.getText() + "\n");
                bw.append("Two French Toast with Bacon ");
                bw.append(sp2TextField.getText());
                bw.newLine();
            }
            if (sp3CheckBox.isSelected()) {
                double sp3;
                sp3 = Double.parseDouble(sp3TextField.getText());
                a = a + sp3 * 300;
                jTextArea1.append("Two Pancakes With Bacon " + "     " + sp3TextField.getText() + "\n");
                bw.append("Two Pancakes With Bacon ");
                bw.append(sp3TextField.getText());
                bw.newLine();

            }
            if (sp4CheckBox.isSelected()) {
                double sp4;
                sp4 = Double.parseDouble(sp4TextField.getText());
                a = a + sp4 * 400;
                jTextArea1.append("Two Pancakes With Two Eggs " + "     " + sp4TextField.getText() + "\n");
                bw.append("Two Pancakes With Two Eggs ");
                bw.append(sp4TextField.getText());
                bw.newLine();
            }
            if (vegCheckBox.isSelected()) {
                double veg;
                veg = Double.parseDouble(vegTextField.getText());
                a = a + veg * 60;
                jTextArea1.append("Vegetable     " + "     " + vegTextField.getText() + "\n");
                bw.append("Vegetable ");
                bw.append(vegTextField.getText());
                bw.newLine();
            }
            if (dalCheckBox.isSelected()) {
                double dal;
                dal = Double.parseDouble(dalTextField.getText());
                a=a +dal *15;
                jTextArea1.append("Dal          " + "     " + dalTextField.getText() + "\n");
                bw.append("Dal ");
                bw.append(dalTextField.getText());
                bw.newLine();
            }

            String s = String.valueOf(a);
            jTextArea1.append("\n\n" + "Total Amount:  " + s);
            bw.append("Total Amount: "+s);
            bw.newLine();
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Input only number ");
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(BreakFast.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void plainCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plainCheckBoxActionPerformed

    private void easternTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easternTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easternTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BreakFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BreakFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BreakFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BreakFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreakFast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ApplejCheckBox;
    private javax.swing.JCheckBox MangoCheckBox;
    private javax.swing.JCheckBox appleCheckBox;
    private javax.swing.JTextField appleTextField;
    private javax.swing.JTextField applejTextField;
    private javax.swing.JCheckBox beefCheckBox;
    private javax.swing.JTextField beefTextField;
    private javax.swing.JCheckBox bluberryCheckBox;
    private javax.swing.JTextField bluberryTextField;
    private javax.swing.JCheckBox bostonCheckBox;
    private javax.swing.JTextField bostonTextField;
    private javax.swing.JCheckBox butterCheckBox;
    private javax.swing.JTextField butterNaanTextField;
    private javax.swing.JCheckBox chickenCheckBox;
    private javax.swing.JTextField chickenTextField;
    private javax.swing.JCheckBox coldCheckBox;
    private javax.swing.JTextField coldTextField;
    private javax.swing.JCheckBox cowCheckBox;
    private javax.swing.JTextField cowTextField;
    private javax.swing.JCheckBox dalCheckBox;
    private javax.swing.JTextField dalTextField;
    private javax.swing.JTextField easternTextField;
    private javax.swing.JCheckBox esternCheckBox;
    private javax.swing.JCheckBox garlicCheckBox;
    private javax.swing.JTextField garlicNaanTextField;
    private javax.swing.JCheckBox hotChoCheckBox;
    private javax.swing.JTextField hotChoTextField;
    private javax.swing.JCheckBox hotCoffeecheckbox;
    private javax.swing.JTextField hotcoffeeTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox kashmeriCheckBox;
    private javax.swing.JTextField kashmeriTextField;
    private javax.swing.JTextField mangoTextField;
    private javax.swing.JCheckBox milkCheckBox;
    private javax.swing.JTextField milkTextField;
    private javax.swing.JCheckBox muttonCheckBox;
    private javax.swing.JTextField muttonTextField;
    private javax.swing.JCheckBox muttonbCheckBox;
    private javax.swing.JTextField muttonbTextField;
    private javax.swing.JCheckBox orangeCheckBox;
    private javax.swing.JTextField orangeTextField;
    private javax.swing.JCheckBox oreoCheckBox;
    private javax.swing.JTextField oreoTextField;
    private javax.swing.JCheckBox parataCheckBox;
    private javax.swing.JTextField parataTextField;
    private javax.swing.JCheckBox plainCheckBox;
    private javax.swing.JTextField plainNaanTextField;
    private javax.swing.JCheckBox plainpCheckBox;
    private javax.swing.JTextField plainpTextField;
    private javax.swing.JCheckBox sp1CheckBox;
    private javax.swing.JTextField sp1TextField;
    private javax.swing.JCheckBox sp2CheckBox;
    private javax.swing.JTextField sp2TextField;
    private javax.swing.JCheckBox sp3CheckBox;
    private javax.swing.JTextField sp3TextField;
    private javax.swing.JCheckBox sp4CheckBox;
    private javax.swing.JTextField sp4TextField;
    private javax.swing.JCheckBox spanishCheckBox;
    private javax.swing.JTextField spanishTextField;
    private javax.swing.JCheckBox teaCheckBox;
    private javax.swing.JTextField teaTextField;
    private javax.swing.JCheckBox vegCheckBox;
    private javax.swing.JTextField vegTextField;
    private javax.swing.JCheckBox veggieCheckBox;
    private javax.swing.JTextField veggieTextField;
    private javax.swing.JCheckBox westernCheckBox;
    private javax.swing.JTextField westernTextField;
    // End of variables declaration//GEN-END:variables
}
