
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fahad
 */
public class Lunch extends javax.swing.JFrame {

    /**
     * Creates new form Lunch
     */
    double a;
    String d = "";

    public Lunch() {
        initComponents();
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("Kachchi Birani");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(40, 100, 210, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Birani & Khichuri");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 70, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Lunch & Dinner");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 0, 320, 30);

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox8.setText("Tehari");
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(40, 400, 210, 25);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox2.setText("Kachchi Birani(with egg)");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(40, 130, 210, 25);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox3.setText("Kachchi Birani(with kabab)");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(40, 160, 210, 25);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox4.setText("Chicken Birani");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(40, 190, 210, 25);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox5.setText("Chicken Birani(with egg)");
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(40, 220, 210, 25);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox6.setText("Chicken Birani(with kabab)");
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(40, 250, 210, 25);

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox7.setText("Plain Polao");
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(40, 280, 210, 25);

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox9.setText("Chicken Bhuna Khichuri");
        jPanel1.add(jCheckBox9);
        jCheckBox9.setBounds(40, 310, 210, 25);

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox10.setText("Mutton Bhuna Khichuri");
        jPanel1.add(jCheckBox10);
        jCheckBox10.setBounds(40, 340, 210, 25);

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox11.setText("Beef Khichuri");
        jPanel1.add(jCheckBox11);
        jCheckBox11.setBounds(40, 370, 210, 25);

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox12.setText("Plain Rice");
        jPanel1.add(jCheckBox12);
        jCheckBox12.setBounds(40, 430, 210, 25);

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox14.setText("Cashewnut Salad");
        jPanel1.add(jCheckBox14);
        jCheckBox14.setBounds(40, 540, 210, 25);

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox13.setText("Grilled Chicken Salad");
        jPanel1.add(jCheckBox13);
        jCheckBox13.setBounds(40, 510, 210, 25);

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox15.setText("Vegetable Salad");
        jPanel1.add(jCheckBox15);
        jCheckBox15.setBounds(40, 570, 210, 25);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(280, 100, 40, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(280, 130, 40, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(280, 160, 40, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(280, 190, 40, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(280, 220, 40, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(280, 250, 40, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(280, 280, 40, 30);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(280, 310, 40, 30);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(280, 340, 40, 30);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(280, 370, 40, 30);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(280, 400, 40, 30);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(280, 430, 40, 30);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(280, 510, 40, 30);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(280, 540, 40, 30);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(280, 570, 40, 30);

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox16.setText("Rupchanda Fry");
        jPanel1.add(jCheckBox16);
        jCheckBox16.setBounds(360, 100, 150, 25);

        jCheckBox17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox17.setText("Fried Oysters ");
        jPanel1.add(jCheckBox17);
        jCheckBox17.setBounds(360, 130, 150, 25);

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox18.setText("Haddock");
        jPanel1.add(jCheckBox18);
        jCheckBox18.setBounds(360, 160, 150, 25);

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox19.setText(" Catfish Filets");
        jPanel1.add(jCheckBox19);
        jCheckBox19.setBounds(360, 190, 150, 25);

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox20.setText("Grouper's Cousine");
        jPanel1.add(jCheckBox20);
        jCheckBox20.setBounds(360, 220, 153, 25);

        jCheckBox21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox21.setText("Dozen Shrimp");
        jPanel1.add(jCheckBox21);
        jCheckBox21.setBounds(360, 250, 150, 25);
        jPanel1.add(jTextField16);
        jTextField16.setBounds(550, 100, 30, 30);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(550, 130, 30, 30);
        jPanel1.add(jTextField18);
        jTextField18.setBounds(550, 160, 30, 30);

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField19);
        jTextField19.setBounds(550, 190, 30, 30);
        jPanel1.add(jTextField20);
        jTextField20.setBounds(550, 220, 30, 30);
        jPanel1.add(jTextField21);
        jTextField21.setBounds(550, 250, 30, 30);

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox22.setText("Borhani");
        jPanel1.add(jCheckBox22);
        jCheckBox22.setBounds(360, 340, 120, 25);

        jCheckBox23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox23.setText("Labang");
        jPanel1.add(jCheckBox23);
        jCheckBox23.setBounds(360, 370, 120, 25);

        jCheckBox24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox24.setText("Mineral Water");
        jPanel1.add(jCheckBox24);
        jCheckBox24.setBounds(360, 400, 120, 25);

        jCheckBox25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox25.setText("Cocacola");
        jPanel1.add(jCheckBox25);
        jCheckBox25.setBounds(360, 430, 120, 25);

        jCheckBox28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox28.setText("carnival Steak");
        jPanel1.add(jCheckBox28);
        jCheckBox28.setBounds(360, 510, 130, 25);

        jCheckBox29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox29.setText("Beef Steak");
        jPanel1.add(jCheckBox29);
        jCheckBox29.setBounds(360, 540, 130, 25);

        jCheckBox30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox30.setText("Chicken Steak");
        jPanel1.add(jCheckBox30);
        jCheckBox30.setBounds(360, 570, 130, 25);
        jPanel1.add(jTextField22);
        jTextField22.setBounds(540, 340, 30, 30);
        jPanel1.add(jTextField23);
        jTextField23.setBounds(540, 370, 30, 30);
        jPanel1.add(jTextField24);
        jTextField24.setBounds(540, 400, 30, 30);

        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField25);
        jTextField25.setBounds(540, 430, 30, 30);
        jPanel1.add(jTextField26);
        jTextField26.setBounds(550, 510, 30, 30);
        jPanel1.add(jTextField27);
        jTextField27.setBounds(550, 540, 30, 30);
        jPanel1.add(jTextField28);
        jTextField28.setBounds(550, 570, 30, 30);

        jCheckBox26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox26.setText("Chicken Roast");
        jPanel1.add(jCheckBox26);
        jCheckBox26.setBounds(640, 100, 140, 25);

        jCheckBox27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox27.setText("Duck Roast");
        jPanel1.add(jCheckBox27);
        jCheckBox27.setBounds(640, 130, 140, 25);

        jCheckBox31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox31.setText("Beef Kala Bhuna");
        jPanel1.add(jCheckBox31);
        jCheckBox31.setBounds(640, 160, 140, 25);

        jCheckBox32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox32.setText("Mutton Curry");
        jPanel1.add(jCheckBox32);
        jCheckBox32.setBounds(640, 190, 140, 25);
        jPanel1.add(jTextField29);
        jTextField29.setBounds(830, 100, 30, 30);
        jPanel1.add(jTextField30);
        jTextField30.setBounds(830, 130, 30, 30);
        jPanel1.add(jTextField31);
        jTextField31.setBounds(830, 160, 30, 30);

        jTextField32.setToolTipText("");
        jPanel1.add(jTextField32);
        jTextField32.setBounds(830, 190, 30, 30);

        jCheckBox33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox33.setText("Fried Rice with Chicken fry");
        jPanel1.add(jCheckBox33);
        jCheckBox33.setBounds(640, 280, 220, 25);

        jCheckBox34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox34.setText("Chicken Red Chilli Suka");
        jPanel1.add(jCheckBox34);
        jCheckBox34.setBounds(640, 310, 220, 25);

        jCheckBox35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox35.setText("Faluda");
        jPanel1.add(jCheckBox35);
        jCheckBox35.setBounds(640, 380, 90, 25);
        jPanel1.add(jTextField33);
        jTextField33.setBounds(920, 280, 30, 30);
        jPanel1.add(jTextField34);
        jTextField34.setBounds(920, 310, 30, 30);

        jCheckBox36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox36.setText("Pudding");
        jPanel1.add(jCheckBox36);
        jCheckBox36.setBounds(640, 410, 90, 25);

        jCheckBox37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox37.setText("Phirni");
        jPanel1.add(jCheckBox37);
        jCheckBox37.setBounds(640, 440, 90, 25);
        jPanel1.add(jTextField35);
        jTextField35.setBounds(780, 380, 40, 30);
        jPanel1.add(jTextField36);
        jTextField36.setBounds(780, 410, 40, 30);
        jPanel1.add(jTextField37);
        jTextField37.setBounds(780, 440, 40, 30);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 510, 80, 23);

        jButton2.setText("Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(600, 540, 80, 23);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(600, 570, 80, 23);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(600, 600, 80, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(690, 480, 340, 150);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dessert ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(640, 350, 70, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Special Item");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(640, 240, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Meat Item");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(640, 70, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Drinks");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 300, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Steaks");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 470, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sea Food");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 70, 80, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Salad");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 470, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/le-champ-des-lunes-restaurant-gastronomique-au-coeur-du-luberon-fond-background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FoodSession fs = new FoodSession();
        fs.setVisible(true);
        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("E yyyy/MM/dd   HH-mm-ss");

        int b = 0;
        b++;
        File f = new File("D:\\History.txt");
        FileWriter fw = null;
        try {
            fw = new FileWriter(f, true);
        } catch (IOException ex) {
            Logger.getLogger(Lunch.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedWriter bw = new BufferedWriter(fw);
        try {
            bw.newLine();
            jTextArea1.setText("FOOD SQUARE " + "\n" + sdf.format(d) + "\n" + "FOOD NAME      QTY" + "\n");

            bw.append("FOOD SQUARE ");
            bw.newLine();
            bw.append(sdf.format(d));
            bw.newLine();
            bw.append("FOOD NAME      QTY");
            bw.newLine();

            if (jCheckBox1.isSelected()) {
                double CheckBox1;
                CheckBox1 = Double.parseDouble(jTextField1.getText());
                a = a + CheckBox1 * 220;
                jTextArea1.append("Kachchi Birani          " + jTextField1.getText() + "\n");
                bw.append("Kachchi Biriani ");
                bw.append(jTextField1.getText());
                bw.newLine();

            }
            if (jCheckBox2.isSelected()) {
                double CheckBox2;
                CheckBox2 = Double.parseDouble(jTextField2.getText());
                a = a + CheckBox2 * 230;
                bw.append("Kachchi Biriani with egg ");
                bw.append(jTextField2.getText());
                bw.newLine();
                jTextArea1.append("Kachchi Birani with egg " + jTextField2.getText() + "\n");
            }
            if (jCheckBox3.isSelected()) {
                double CheckBox3;
                CheckBox3 = Double.parseDouble(jTextField3.getText());
                a = a + CheckBox3 * 270;
                jTextArea1.append("Kachchi Birani with Kabab " + jTextField3.getText() + "\n");
                bw.append("Kachchi Biriani with kabab ");
                bw.append(jTextField3.getText());
                bw.newLine();

            }
            if (jCheckBox4.isSelected()) {
                double CheckBox4;
                CheckBox4 = Double.parseDouble(jTextField4.getText());
                a = a + CheckBox4 * 200;
                jTextArea1.append("Chicken Birani          " + jTextField4.getText() + "\n");
                bw.append("Chicken Biriani ");
                bw.append(jTextField4.getText());
                bw.newLine();
            }
            if (jCheckBox5.isSelected()) {
                double CheckBox5;
                CheckBox5 = Double.parseDouble(jTextField5.getText());
                a = a + CheckBox5 * 220;
                jTextArea1.append("Chicken Birani with egg" + jTextField5.getText() + "\n");
                bw.append("Chicken Biriani with egg ");
                bw.append(jTextField5.getText());
                bw.newLine();
            }
            if (jCheckBox6.isSelected()) {
                double CheckBox6;
                CheckBox6 = Double.parseDouble(jTextField6.getText());
                a = a + CheckBox6 * 240;
                jTextArea1.append("Chicken Birani with kabab" + jTextField6.getText() + "\n");
                bw.append("Chicken Biriani with kabab ");
                bw.append(jTextField6.getText());
                bw.newLine();

            }
            if (jCheckBox7.isSelected()) {
                double CheckBox7;
                CheckBox7 = Double.parseDouble(jTextField7.getText());
                a = a + CheckBox7 * 70;
                jTextArea1.append("Plain polao             " + jTextField7.getText() + "\n");
                bw.append("plain Polao ");
                bw.append(jTextField7.getText());
                bw.newLine();
            }
            if (jCheckBox8.isSelected()) {
                double CheckBox8;
                CheckBox8 = Double.parseDouble(jTextField8.getText());
                a = a + CheckBox8 * 200;
                jTextArea1.append("Chicken Bhuna Khichuri  " + jTextField8.getText() + "\n");
                bw.append("Chicken Bhuna Khichuri ");
                bw.append(jTextField8.getText());
                bw.newLine();
            }
            if (jCheckBox9.isSelected()) {
                double CheckBox9;
                CheckBox9 = Double.parseDouble(jTextField9.getText());
                a = a + CheckBox9 * 250;
                jTextArea1.append("Mutton Bhuna Khichuri   " + jTextField9.getText() + "\n");
                bw.append("Mutton Bhuna Khichuri ");
                bw.append(jTextField9.getText());
                bw.newLine();
            }
            if (jCheckBox10.isSelected()) {
                double CheckBox10;
                CheckBox10 = Double.parseDouble(jTextField10.getText());
                a = a + CheckBox10 * 170;
                jTextArea1.append("Beef Khichuri           " + jTextField10.getText() + "\n");
                bw.append("Beef Khichuri ");
                bw.append(jTextField10.getText());
                bw.newLine();
            }
            if (jCheckBox11.isSelected()) {
                double CheckBox11;
                CheckBox11 = Double.parseDouble(jTextField11.getText());
                a = a + CheckBox11 * 170;
                jTextArea1.append("Tehani                  " + jTextField11.getText() + "\n");
                bw.append("Tehari ");
                bw.append(jTextField11.getText());
                bw.newLine();
            }
            if (jCheckBox12.isSelected()) {
                double CheckBox12;
                CheckBox12 = Double.parseDouble(jTextField12.getText());
                a = a + CheckBox12 * 30;
                jTextArea1.append("plain Rice               " + jTextField12.getText() + "\n");
                bw.append("Plain Rice ");
                bw.append(jTextField12.getText());
                bw.newLine();
            }
            if (jCheckBox13.isSelected()) {
                double CheckBox13;
                CheckBox13 = Double.parseDouble(jTextField13.getText());
                a = a + CheckBox13 * 300;
                jTextArea1.append("Grilled Chicken Salad    " + jTextField13.getText() + "\n");
                bw.append("Grilled Chicken Salad ");
                bw.append(jTextField13.getText());
                bw.newLine();
            }
            if (jCheckBox14.isSelected()) {
                double CheckBox14;
                CheckBox14 = Double.parseDouble(jTextField14.getText());
                a = a + CheckBox14 * 350;
                jTextArea1.append("Cashewnut Salad    " + jTextField14.getText() + "\n");
                bw.append("Cashewnut ");
                bw.append(jTextField14.getText());
                bw.newLine();
            }
            if (jCheckBox15.isSelected()) {
                double CheckBox15;
                CheckBox15 = Double.parseDouble(jTextField15.getText());
                a = a + CheckBox15 * 100;
                jTextArea1.append("Vegetable Salad    " + jTextField15.getText() + "\n");
                bw.append("Vegetable Salad ");
                bw.append(jTextField15.getText());
                bw.newLine();
            }
            if (jCheckBox16.isSelected()) {
                double CheckBox16;
                CheckBox16 = Double.parseDouble(jTextField16.getText());
                a = a + CheckBox16 * 510;
                jTextArea1.append("Rupchanda Fry   " + jTextField16.getText() + "\n");
                bw.append("Rupchada Fry  ");
                bw.append(jTextField16.getText());
                bw.newLine();
            }
            if (jCheckBox17.isSelected()) {
                double CheckBox17;
                CheckBox17 = Double.parseDouble(jTextField17.getText());
                a = a + CheckBox17 * 880;
                jTextArea1.append("Fried Oysters    " + jTextField17.getText() + "\n");
                bw.append("Fried oysters ");
                bw.append(jTextField17.getText());
                bw.newLine();
            }
            if (jCheckBox18.isSelected()) {
                double CheckBox18;
                CheckBox18 = Double.parseDouble(jTextField18.getText());
                a = a + CheckBox18 * 1200;
                jTextArea1.append("Haddock              " + jTextField18.getText() + "\n");
                bw.append("Haddock ");
                bw.append(jTextField18.getText());
                bw.newLine();
            }
            if (jCheckBox19.isSelected()) {
                double CheckBox19;
                CheckBox19 = Double.parseDouble(jTextField19.getText());
                a = a + CheckBox19 * 430;
                jTextArea1.append(" Catfish Filets       " + jTextField19.getText() + "\n");
                bw.append("Catfish filets ");
                bw.append(jTextField19.getText());
                bw.newLine();
            }
            if (jCheckBox20.isSelected()) {
                double CheckBox20;
                CheckBox20 = Double.parseDouble(jTextField20.getText());
                a = a + CheckBox20 * 650;
                jTextArea1.append("Grouper's Cousine      " + jTextField20.getText() + "\n");
                bw.append("Group's cousine ");
                bw.append(jTextField20.getText());
                bw.newLine();
            }
            if (jCheckBox21.isSelected()) {
                double CheckBox21;
                CheckBox21 = Double.parseDouble(jTextField21.getText());
                a = a + CheckBox21 * 640;
                jTextArea1.append("Dozen Shrimp         " + jTextField21.getText() + "\n");
                bw.append("Dozen Shrimp ");
                bw.append(jTextField21.getText());
                bw.newLine();
            }
            if (jCheckBox22.isSelected()) {
                double CheckBox22;
                CheckBox22 = Double.parseDouble(jTextField22.getText());
                a = a + CheckBox22 * 45;
                jTextArea1.append("Borhani              " + jTextField22.getText() + "\n");
                bw.append("Borhani ");
                bw.append(jTextField22.getText());
                bw.newLine();
            }
            if (jCheckBox23.isSelected()) {
                double CheckBox23;
                CheckBox23 = Double.parseDouble(jTextField23.getText());
                a = a + CheckBox23 * 40;
                jTextArea1.append("Labang               " + jTextField23.getText() + "\n");
                bw.append("Labang ");
                bw.append(jTextField23.getText());
                bw.newLine();
            }
            if (jCheckBox24.isSelected()) {
                double CheckBox24;
                CheckBox24 = Double.parseDouble(jTextField24.getText());
                a = a + CheckBox24 * 25;
                jTextArea1.append("Mineral Water         " + jTextField24.getText() + "\n");
                bw.append("Mineral water");
                bw.append(jTextField24.getText());
                bw.newLine();
            }
            if (jCheckBox25.isSelected()) {
                double CheckBox25;
                CheckBox25 = Double.parseDouble(jTextField25.getText());
                a = a + CheckBox25 * 30;
                jTextArea1.append("Cocacola            " + jTextField25.getText() + "\n");
                bw.append("Cocacola ");
                bw.append(jTextField25.getText());
                bw.newLine();
            }
            if (jCheckBox26.isSelected()) {
                double CheckBox26;
                CheckBox26 = Double.parseDouble(jTextField29.getText());
                a = a + CheckBox26 * 230;
                jTextArea1.append("Chicken Roast           " + jTextField29.getText() + "\n");
                bw.append("Chicken Roast ");
                bw.append(jTextField29.getText());
                bw.newLine();
            }
            if (jCheckBox27.isSelected()) {
                double CheckBox27;
                CheckBox27 = Double.parseDouble(jTextField30.getText());
                a = a + CheckBox27 * 270;
                jTextArea1.append("Duck Roast           " + jTextField30.getText() + "\n");
                bw.append("Duck Roast ");
                bw.append(jTextField30.getText());
                bw.newLine();
            }
            if (jCheckBox31.isSelected()) {
                double CheckBox31;
                CheckBox31 = Double.parseDouble(jTextField31.getText());
                a = a + CheckBox31 * 200;
                jTextArea1.append("Beef Kala Bhuna        " + jTextField31.getText() + "\n");
                bw.append("Beef Kala Bhuna ");
                bw.append(jTextField31.getText());
                bw.newLine();
            }
            if (jCheckBox32.isSelected()) {
                double CheckBox32;
                CheckBox32 = Double.parseDouble(jTextField32.getText());
                a = a + CheckBox32 * 270;
                jTextArea1.append("Mutton Curry          " + jTextField32.getText() + "\n");
                bw.append("Mutton Curry ");
                bw.append(jTextField32.getText());
                bw.newLine();
            }
            if (jCheckBox33.isSelected()) {
                double CheckBox33;
                CheckBox33 = Double.parseDouble(jTextField33.getText());
                a = a + CheckBox33 * 350;
                jTextArea1.append("Fried Rice with Chicken fry  " + jTextField33.getText() + "\n");
                bw.append("Fried Rice with Chicken Fry ");
                bw.append(jTextField33.getText());
                bw.newLine();
            }
            if (jCheckBox34.isSelected()) {
                double CheckBox34;
                CheckBox34 = Double.parseDouble(jTextField34.getText());
                a = a + CheckBox34 * 350;
                jTextArea1.append("Chicken Red Chilli Suka     " + jTextField34.getText() + "\n");
                bw.append("Chicken Red Chilli Suka ");
                bw.append(jTextField34.getText());
                bw.newLine();
            }
            if (jCheckBox35.isSelected()) {
                double CheckBox35;
                CheckBox35 = Double.parseDouble(jTextField35.getText());
                a = a + CheckBox35 * 80;
                jTextArea1.append("Faluda          " + jTextField35.getText() + "\n");
                bw.append("Faluda ");
                bw.append(jTextField35.getText());
                bw.newLine();
            }
            if (jCheckBox36.isSelected()) {
                double CheckBox36;
                CheckBox36 = Double.parseDouble(jTextField36.getText());
                a = a + CheckBox36 * 80;
                jTextArea1.append("Pudding         " + jTextField36.getText() + "\n");
                bw.append("Pudding ");
                bw.append(jTextField36.getText());
                bw.newLine();
            }
            if (jCheckBox37.isSelected()) {
                double CheckBox37;
                CheckBox37 = Double.parseDouble(jTextField37.getText());
                a = a + CheckBox37 * 75;
                jTextArea1.append("Phirni          " + jTextField37.getText() + "\n");
                bw.append("Phirni ");
                bw.append(jTextField37.getText());
                bw.newLine();
            }
            if (jCheckBox28.isSelected()) {
                double CheckBox28;
                CheckBox28 = Double.parseDouble(jTextField26.getText());
                a = a + CheckBox28 * 300;
                jTextArea1.append("Carnival Steak          " + jTextField26.getText() + "\n");
                bw.append("Carnival Steak ");
                bw.append(jTextField26.getText());
                bw.newLine();
            }
            if (jCheckBox29.isSelected()) {
                double CheckBox29;
                CheckBox29 = Double.parseDouble(jTextField27.getText());
                a = a + CheckBox29 * 270;
                jTextArea1.append("Beef Steak          " + jTextField27.getText() + "\n");
                bw.append("Beef Steak ");
                bw.append(jTextField27.getText());
                bw.newLine();
            }
            if (jCheckBox30.isSelected()) {
                double CheckBox30;
                CheckBox30 = Double.parseDouble(jTextField28.getText());
                a = a + CheckBox30 * 250;
                jTextArea1.append("Mashroom Steak          " + jTextField28.getText() + "\n");
                bw.append("Mashroom Steak ");
                bw.append(jTextField28.getText());
                bw.newLine();
            }

            String s = String.valueOf(a);
            jTextArea1.append("\n\n" + "Total Amount:  " + s);
            bw.append("Total Amount: "+s);
            bw.newLine();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Input only number ");
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Lunch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        a = 0;
        jTextArea1.setText("");
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        jCheckBox12.setSelected(false);
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);
        jCheckBox20.setSelected(false);
        jCheckBox21.setSelected(false);
        jCheckBox22.setSelected(false);
        jCheckBox23.setSelected(false);
        jCheckBox24.setSelected(false);
        jCheckBox25.setSelected(false);
        jCheckBox26.setSelected(false);
        jCheckBox27.setSelected(false);
        jCheckBox31.setSelected(false);
        jCheckBox32.setSelected(false);
        jCheckBox33.setSelected(false);
        jCheckBox34.setSelected(false);
        jCheckBox35.setSelected(false);
        jCheckBox36.setSelected(false);
        jCheckBox37.setSelected(false);
        jCheckBox28.setSelected(false);
        jCheckBox29.setSelected(false);
        jCheckBox30.setSelected(false);

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField29.setText("");
        jTextField30.setText("");
        jTextField31.setText("");
        jTextField32.setText("");
        jTextField33.setText("");
        jTextField34.setText("");
        jTextField35.setText("");
        jTextField36.setText("");
        jTextField37.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        jTextField28.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lunch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
